name: Main workflow

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          version: 18.x
      - name: npm install, lint, and test
        run: |
          npm install
          npm run lint:build
          npm test
  deploy_now:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: deploy
        uses: actions/zeit-now@master
        env:
          ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
